### ISSUE TITLE
adding gif for readme

### ISSUE THREAD

**Issue by 1bitphoenix** [ryuzaki3/Todo-List#1]
![addnewtodos](https://user-images.githubusercontent.com/29941303/52488335-993e1a80-2be5-11e9-8eee-eb5e37449aff.gif)
![doneundone](https://user-images.githubusercontent.com/29941303/52488348-a3601900-2be5-11e9-8651-e47d3a3ef749.gif)
![deletetodo](https://user-images.githubusercontent.com/29941303/52488379-b5da5280-2be5-11e9-949a-b6bf5fb2e758.gif)

**Comment by ryuzaki3** [comment]
![videotogif_2018 12 26_20 34 04](https://user-images.githubusercontent.com/29941303/50449554-1ff8aa00-094e-11e9-80dd-06072fbeea47.gif)
